security:

    encoders:
        TK\UserManagerBundle\Entity\User: plaintext

    providers:
        database:
            entity: { class: TKUserManagerBundle:User, property: email }

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /signin
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: /user/$, roles: IS_AUTHENTICATED_FULLY }
        - { path: /user/(\d)+$, roles: IS_AUTHENTICATED_FULLY }
        - { path: /edit$, roles: IS_AUTHENTICATED_FULLY }