TK\UserManagerBundle\Entity\UserRole:
    type: entity
    repositoryClass: TK\UserManagerBundle\Repository\UserRoleRepository
    table: userRoles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime
            column: created_at
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            nullable: true
    oneToMany:
        users:
            targetEntity: User
            mappedBy: userRole
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
        preUpdate: [setUpdatedAtValue]